### PR TITLE
replace the css`` path using constructed ast to avoid plugin conflicts

### PR DESCRIPTION
**Pull request by tkh44**
All of the examples of this would need to be updated as well. I just changed this one to get the ball rolling. 

As a bonus, this change allows for `attr` css value support in [tkh44/emotion](https://github.com/tkh44/emotion).

### CODE REVIEW

**Review by tkh44 — COMMENTED** [review]
Key changes are here: https://github.com/threepointone/glam/pull/10/files?w=1#diff-bb35c33015964b91f5c83deb2a33a814R200

**Comment by threepointone** [comment]
You should now have full commit access. Have fun :)

**Comment by tkh44** [comment]
I don't think it worked 😐

**Comment by threepointone** [comment]
There should be an invite in your email, you need to accept it

**Pull request merged**
